#!/bin/bash
a=`cat <<-EOF
https://github.com/urbanesec/ZackAttack.git
https://github.com/rogueclown/recon-scripts.git
https://bitbucket.org/LaNMaSteR53/recon-ng.git
https://bitbucket.org/LaNMaSteR53/honeybadger.git
https://bitbucket.org/LaNMaSteR53/peepingtom.git
http://ptscripts.googlecode.com/svn/trunk/windows/vssown.vbs
https://github.com/toolswatch/DPE.git
https://github.com/mubix/post-exploitation.git
https://github.com/1aN0rmus/TekDefense-Automater.git
https://github.com/ornicar/backdoor.git
https://github.com/SpiderLabs/BurpNotesExtension.git
https://github.com/SmeegeSec/WSDLWizard.git
https://github.com/Meatballs1/burp-extensions.git
https://github.com/abhijitsverma/burp_extension_MultiScanner.git
https://github.com/SpiderLabs/UPnP-request-generator.git
https://github.com/moxie0/sslstrip.git
https://github.com/moxie0/sslsniff.git
https://github.com/GDSSecurity/PadBuster.git
https://github.com/nealharris/BREACH.git
https://github.com/sqlmapproject/sqlmap.git
https://github.com/Neohapsis/bbqsql.git
https://github.com/GDSSecurity/SQLBrute.git
https://github.com/7a/owtf.git
https://github.com/beefproject/beef.git
https://github.com/ianic/mssql.git
https://github.com/milo2012/osintstalker.git
https://github.com/mossmann/hackrf.git
https://github.com/rsmudge/cortana-scripts.git
https://github.com/mubix/vt-notify.git
https://github.com/wick2o/gitDigger.git
https://github.com/Hood3dRob1n/ShodanAPI.git
https://github.com/jvehent/cipherscan.git
https://github.com/gps-sdr/gps-sdr.git
https://github.com/azet/Software-Defined-Radio.git
https://github.com/kpreid/shinysdr.git
https://github.com/csete/gqrx.git
https://github.com/texane/nrf.git
https://github.com/EliasOenal/multimon-ng.git
https://github.com/b00stfr3ak/misc.git
https://github.com/brav0hax/smbexec.git
https://github.com/b00stfr3ak/fast_meterpreter.git
https://code.google.com/p/lazykali/
git://git.gnumonks.org/airprobe.git
git://git.srlabs.de/kraken.git
https://github.com/fgont/ipv6toolkit.git
https://github.com/mattifestation/PowerSploit.git
https://github.com/urbanadventurer/WhatWeb.git
https://github.com/mhendrickx/Lilith.git
https://github.com/cr0hn/golismero.git
https://github.com/mandatoryprogrammer/xssless.git
https://github.com/zmap/zmap.git
https://github.com/robertdavidgraham/masscan.git
https://github.com/tiwaryshailesh/Masscan-For-Metasploit.git
https://github.com/macubergeek/gitlist.git
https://github.com/opinkerfi/winexe.git
https://github.com/kanzure/python-wmi-client-wrapper.git
https://gist.github.com/9107276.git
https://github.com/PenturaLabs/Linux_Exploit_Suggester.git
https://github.com/mmoya/pkg-thc-ipv6.git
https://github.com/bastibl/gr-rds.git
https://github.com/Hood3dRob1n/creep3r.git
https://github.com/fgont/ipv6toolkit.git
https://github.com/mmoya/pkg-thc-ipv6.git
https://github.com/leebaird/discover.git
https://github.com/lightos/Panoptic.git
https://github.com/QBurst/PenQ.git
https://github.com/MooseDojo/Serpico.git
https://github.com/SpiderLabs/Responder.git
https://github.com/mattifestation/PowerSploit.git
https://github.com/TigerSecurity/gerix-wifi-cracker.git
http://www.openvas.org/download/wmi/wmi-1.3.14.tar.bz2:
https://github.com/wpscanteam/wpscan.git
https://github.com/mubix/WhiteChapel.git
https://gist.github.com/10107280.git
https://gist.github.com/9107284.git
https://gist.github.com/9107276.git
https://github.com/mmessano/PowerShell.git
https://github.com/brav0hax/easy-creds.git
https://github.com/felmoltor/DNSSnoopDogg.git
https://github.com/robertdavidgraham/heartleech.git
git://git.openssl.org/openssl.git
https://github.com/mubix/netview.git
https://github.com/mubix/WhiteChapel.git
git://github.com/anestisb/WeBaCoo.git
https://gist.github.com/5371322.git
https://github.com/slattman/php-reverse-shell.git
git://github.com/zacinaction/kicksat.wiki.git
https://github.com/inquisb/keimpx.git
https://github.com/TheRook/subbrute.git
https://gist.github.com/10171593.git
https://github.com/rsmudge/metasploit-loader.git
https://gist.github.com/b54e50a3dddfb3fadd0a.git
https://github.com/jekyc/wig.git
https://github.com/bastibl/gr-ieee802-11.git
https://github.com/dcramer/chardet.git
https://github.com/client9/sslassert.git
https://github.com/toddsiegel/spscan.git
https://github.com/EarToEarOak/RTLSDR-Scanner.git
https://github.com/kevinmehall/rtlsdr-433m-sensor.git
https://github.com/bemasher/rtlamr.git
https://github.com/nickodell/morse-code.git
https://github.com/merbanan/rtl_433.git
https://github.com/sensepost/mana.git
https://github.com/ksnieck/airprobe.git
https://github.com/rasta-mouse/Mjolnir.git
https://github.com/Netflix/Scumblr.git
https://github.com/Netflix/Workflowable.git
https://github.com/Netflix/sketchy.git
https://github.com/mutability/rtl-sdr.git
https://github.com/csete/gnuradio-grc-examples.git
http://git.gnuradio.org/git/gnuradio.git
https://github.com/omriiluz/NRF24-BTLE-Decoder.git
https://github.com/bemasher/rtlamr.git
https://github.com/eT0M/rtl_sdr_FS20_decoder.git
https://github.com/jacobzelek/rtl_sdr_kit.git
https://github.com/yuvadm/gascop.git
https://github.com/antirez/dump1090.git
https://github.com/skaringa/weather-sdr-decode.git
https://github.com/Nuand/bladeRF.git
https://github.com/allfro/sploitego.git
https://github.com/balle/bluediving.git
https://github.com/tkuester/gr-psk31.git
https://github.com/bgamari/gnuradio-multimode.git
https://github.com/secretsquirrel/the-backdoor-factory.git
https://github.com/secretsquirrel/BDFProxy
git://git.osmocom.org/sdrangelove.git
https://github.com/OWASP/O-Saft.git
https://github.com/rockymeza/wifi.git
https://github.com/clockfort/wifi-locator.git
https://github.com/OpenSecurityResearch/hostapd-wpe.git
https://github.com/windytan/slowrx.git
https://github.com/offensive-security/kali-sly-pi.git
https://github.com/AdamLaurie/RFIDIOt.git
https://github.com/Proxmark/proxmark3.git
https://github.com/rezeusor/killerbee.git
https://github.com/CoreSecurity/impacket.git
https://github.com/Miserlou/Hash-Identifier.git
https://github.com/freaklabs/chibiArduino.git
https://bitbucket.org/skew/gyuto.git
https://github.com/fishnetsecurity/Lair.git
https://github.com/ctfs/write-ups.git
https://github.com/trustedsec/unicorn.git
https://github.com/poweradminllc/PAExec.git
https://github.com/HarmJ0y/PowerUp.git
https://github.com/zeknox/scripts.git
https://github.com/darkoperator/Posh-SecMod.git
https://github.com/besimorhino/powercat.git
https://github.com/vacmf/powershell-scripts.git
https://github.com/silentbreaksec/Throwback.git
https://github.com/TweekFawkes/White_Lightning.git
https://github.com/kirill85/BlackSquirrel.git
git://w1.fi/hostap.git
https://github.com/SilverFoxx/PwnSTAR.git
https://github.com/nidem/kerberoast.git
https://github.com/silentbreaksec/ThrowbackLP.git
https://github.com/roeyk/nessus-report.git
https://github.com/travisgoodspeed/goodfet goodfet
https://github.com/robotastic/smartnet-scanner.git
https://github.com/pinkavaj/gr-scan.git
https://github.com/jboone/tpms.git
https://github.com/sitsec/bruteforce-crc.git
https://github.com/nccgroup/metasploitavevasion.git
https://github.com/pentestgeek/phishing-frenzy.git
https://github.com/pentestgeek/phishing-frenzy-templates.git
https://github.com/AdamLaurie/RFIDIOt.git
https://github.com/rainkid/httrack.git
https://github.com/junks/linkedInScraper.git
https://bitbucket.org/al14s/rawr.git
https://github.com/rebootuser/LinEnum.git
https://github.com/bidord/pykek.git
https://github.com/moxie0/chapcrack.git
https://github.com/0xsauby/yasuo.git
https://bitbucket.org/R4v3N/wp-plug.git
https://github.com/leechristensen/UnmanagedPowerShell.git
https://github.com/trustedsec/hash_parser.git
https://github.com/smunaut/osmo-pocsag.git
https://github.com/bafe/gr-pocsag.git
git://git.osmocom.org/gr-osmosdr
https://github.com/mitmproxy/mitmproxy.git
https://github.com/vk496/linset.git
https://github.com/galkan/crowbar
https://github.com/covertcodes/freqwatch.git
https://github.com/sixdub/Minions.git
git://github.com/kennethreitz/requests.git
https://github.com/wireghoul/dotdotpwn.git
https://github.com/superkojiman/dirtshell.git
https://github.com/superkojiman/rfishell.git
https://github.com/ikkisoft/bradamsa.git
https://github.com/smicallef/spiderfoot.git
https://github.com/invisiblethreat/peeper.git
https://github.com/devttys0/binwalk.git
https://github.com/devttys0/binwalk.wiki.git
https://github.com/TweekFawkes/White_Lightning.git
https://github.com/danielmiessler/SecLists.git
https://code.google.com/p/patator/
https://github.com/argilo/sdr-examples.git
https://github.com/milo2012/metasploitHelper.git
https://github.com/Veil-Framework/Veil-Evasion.git
https://github.com/Veil-Framework/PowerTools.git
https://github.com/Veil-Framework/Veil.git
https://github.com/Veil-Framework/Veil-Pillage.git
https://github.com/Veil-Framework/Veil-Catapult.git
https://github.com/SmeegeSec/HashTag.git
https://github.com/gentilkiwi/mimikatz.git
https://github.com/malerisch/burp-csj.git
https://github.com/ShawnDEvans/smbmap.git
https://github.com/stephenfewer/ReflectiveDLLInjection.git
https://github.com/SecureNetworkManagement/shellshockUAscanner.git
https://github.com/glentregoning/mitmtest.git
https://github.com/rebootuser/LinEnum.git
https://github.com/sethsec/crossdomain-exploitation-framework.git
https://github.com/gursev/flash-xdomain-xploit.git
https://github.com/NetSPI/Wsdler/archive/master.zip
https://github.com/rustyrobot/fuzzdb.git
https://github.com/iagox86/dnscat2.git
https://github.com/sixdub/DomainTrustExplorer.git
https://github.com/docker/docker.git
https://github.com/stasinopoulos/commix.git
https://github.com/hatRiot/zarp.git
https://github.com/infobyte/faraday.git
https://github.com/Hood3dRob1n/addicted2hash.git
https://github.com/byt3bl33d3r/gcat.git 
https://github.com/enigma0x3/Generate-Macro.git
https://github.com/tcstool/NoSQLMap.git
https://github.com/cheetz/pi_phone_home.git
https://github.com/cheetz/spearphishing.git
https://github.com/cheetz/adobe_password_checker.git
https://github.com/cheetz/Web_Password_Gen.git
https://github.com/cheetz/brutescrape.git
https://github.com/MaYaSeVeN/Wmap.git
https://github.com/sophron/wifiphisher.git
https://github.com/cheetz/Easy-P.git
https://github.com/michenriksen/gitrob.git
https://github.com/secforce/sparta.git
https://github.com/breenmachine/httpscreenshot.git
https://github.com/ChrisTruncer/EyeWitness.git
https://github.com/HackerFantastic/Public.git
https://github.com/cheetz/icmpshock.git
https://github.com/rapid7/ssh-badkeys.git
https://github.com/sbehrens/sleepy-puppy.git
https://github.com/trustedsec/social-engineer-toolkit.git
https://github.com/tatanus/SPF.git
https://github.com/obscuresec/random.git
https://github.com/jkakavas/creepy.git
https://github.com/evilsocket/bettercap.git
https://github.com/EiNSTeiN-/poodle.git
https://github.com/mpgn/poodle-exploit.git
https://github.com/JayBeale/middler.git
https://github.com/felmoltor/DNSSnoopDogg.git
https://github.com/z0mbiehunt3r/dns-snoopy.git
https://github.com/GDSSecurity/SSH-Weak-DH.git
https://github.com/trustedsec/ptf
https://github.com/trustedsec/meterssh.git
https://github.com/PowerShellEmpire/Empire.git
https://github.com/spinkham/skipfish.git
https://github.com/RetireJS/retire.js.git
https://github.com/jhaddix/domain.git
https://github.com/Dionach/CMSmap.git
https://github.com/intrigueio/intrigue-core.git
https://github.com/debasishm89/burpy.git
https://github.com/arvinddoraiswamy/mywebappscripts.git
https://github.com/jhaddix/domain.git
https://github.com/jhaddix/tbhm.git
https://github.com/NytroRST/NetRipper.git
https://github.com/Ali-Razmjoo/OWASP-ZSC.git
https://github.com/Smaash/snitch.git
https://github.com/google/binnavi.git
https://github.com/dagorim/api_wordlist.git
https://github.com/enjoiz/XXEinjector.git
https://github.com/yorickdewid/Wordgen.git
https://github.com/gojhonny/CredCrack.git
https://github.com/AbhishekGhosh/FREAK-Attack-CVE-2015-0204-Testing-Script.git
https://github.com/IFGHou/Grendel-Scan.git
https://github.com/aircrack-ng/aircrack-ng.git
https://github.com/twilsonb/jbrofuzz.git
https://github.com/pentestmonkey/unix-privesc-check.git
https://github.com/ajinabraham/YSO-Mobile-Security-Framework.git
https://github.com/linux-can/can-utils.git
https://github.com/RUB-NDS/WS-Attacker.git
https://github.com/vetsin/SamlSnort.git
https://github.com/mandatoryprogrammer/sonar.git
https://github.com/milo2012/osintstalker.git
https://github.com/exitnode/nmap-sqlite-output.git
https://github.com/nmap/nmap.git
https://github.com/LionSec/wifresti.git
https://github.com/dloss/python-pentest-tools.git
https://github.com/tiwaryshailesh/MetasploitOnSteroids.git
https://github.com/mattifestation/WMI_Backdoor.git
https://github.com/NetSPI/cmdsql.git
https://github.com/brad-anton/freeradius-wpe.git
https://github.com/b00stfr3ak/fast_meterpreter.git
https://github.com/tennc/webshell.git
https://raw.githubusercontent.com/musalbas/heartbleed-masstest/master/ssltest.py
https://gist.github.com/10100394.git
https://gist.github.com/10174134.git
https://github.com/decal/ssltest-stls.git
https://github.com/ajinabraham/Static-DOM-XSS-Scanner.git
https://github.com/gbrindisi/xsssniper.git
https://github.com/portcullislabs/xssshell-xsstunnell.git
https://github.com/portcullislabs/rdp-sec-check.git
https://github.com/averagesecurityguy/scripts.git
https://github.com/MooseDojo/praedasploit.git
https://github.com/byt3bl33d3r/CrackMapExec.git
https://bitbucket.org/mattinfosec/wordhound.git
https://github.com/cheetz/reddit_xss.git
https://github.com/epinna/weevely3.git
https://github.com/fireeye/synfulknock.git
https://gist.github.com/4461a4853ba0741b2a29.git
https://gist.github.com/1c4e34af21acb679641a.git
https://github.com/evilpacket/DVCS-Pillage.git
https://github.com/SYWorks/wifi-harvester.git
https://github.com/drwetter/testssl.sh.git
https://github.com/kussic/arlandria.git
https://github.com/SYWorks/network_harvester.git
https://github.com/SYWorks/wpa-bruteforcer.git
https://github.com/AnimeshShaw/Hash-Algorithm-Identifier.git
https://github.com/hybridus/heartbleedscanner.git
https://github.com/hybridus/heartbleedscanner.git
https://github.com/ChrisTruncer/Just-Metadata.git
https://bitbucket.org/clr2of8/autoscanwithburp.git
https://github.com/Shellntel/scripts.git
https://github.com/cornerpirate/ReportCompiler.git
https://github.com/funoverip/epowner.git
https://github.com/foreni-packages/cisco-global-exploiter.git
https://github.com/sandrogauci/tftptheft.git
https://github.com/1N3/Findsploit.git
https://github.com/CoderPirata/XPL-SEARCH.git
https://github.com/xdistro/ShellShock.git
https://github.com/jumanjihouse/docker-ssllabs-scan.git
https://github.com/ChrisTruncer/Just-Metadata.git
https://github.com/Hypsurus/weeman.git
https://github.com/SSTCYR/nipper-ng.git
https://github.com/droe/sslsplit
https://github.com/Kevin-Robertson/Inveigh.git
https://github.com/NullArray/PyCat.git
https://github.com/strictlymike/tools.git
https://github.com/sullo/nikto.git
https://github.com/ZilentJack/Get-ADHashDump.git
https://github.com/dolevf/tracetester.git
https://github.com/CoderPirata/XPL-SEARCH.git
https://github.com/offwidth/http-tunnel-aes.git
https://github.com/denandz/KeeFarce.git
https://github.com/maurosoria/dirs3arch.git
https://github.com/techgaun/github-dorks.git
https://github.com/jgor/dork-cli.git
https://github.com/quackware/dorky.git
https://gist.github.com/5950305.git
https://github.com/fuzzdb-project/fuzzdb.git
https://github.com/kahunalu/pwnbin.git
https://github.com/secabstraction/PowerCat.git
https://github.com/samratashok/nishang.git
https://github.com/ChrisTruncer/Egress-Assess.git
https://github.com/nccgroup/chuckle.git
https://github.com/ChrisTruncer/WMIOps.git
https://github.com/psypanda/hashID.git
https://github.com/n1nj4sec/pupy.git
https://github.com/silentbreaksec/UnmanagedPowerShell.git
https://github.com/silentbreaksec/Throwback.git
https://github.com/silentbreaksec/ThrowbackLP.git
https://github.com/silentbreaksec/Trebuchet.git
https://github.com/hfiref0x/UACME.git
https://github.com/0xd4d/dnSpy.git
https://github.com/1N3/Sn1per.git
https://github.com/pentestmonkey/windows-privesc-check.git
https://github.com/samratashok/Kautilya.git
https://github.com/danielmiessler/RobotsDisallowed.git
https://github.com/HarmJ0y/CheatSheets.git
https://github.com/ParrotSec/alternate-install.git
https://github.com/securitytube/wifiscanvisualizer.git
https://github.com/commonexploits/livehosts.git
https://github.com/commonexploits/dtpscan.git
https://github.com/commonexploits/weape.git
https://github.com/commonexploits/weape.git
https://github.com/commonexploits/port-scan-automation.git
https://github.com/commonexploits/winocphc.git
https://github.com/commonexploits/vlan-hopping.git
https://github.com/nccgroup/easyda.git
https://github.com/nccgroup/cisco-SNMP-enumeration.git
https://github.com/juliocesarfort/netscreen-shodan-scanner.git
https://github.com/herrbischoff/awesome-osx-command-line.git
https://github.com/vanhauser-thc/thc-hydra.git
https://github.com/jkbrzt/httpie.git
https://github.com/mandatoryprogrammer/FlashHTTPRequest.git
https://github.com/hatRiot/clusterd.git
https://github.com/nvbn/everpad.git
https://github.com/paramiko/paramiko.git
https://github.com/scadastrangelove/SCADAPASS.git
https://github.com/leonteale/pentestpackage.git
https://github.com/commonexploits/whatsfree.git
https://github.com/commonexploits/dtpscan.git
https://github.com/commonexploits/weape.git
https://github.com/commonexploits/vlan-hopping.git
https://github.com/nccgroup/cisco-SNMP-enumeration.git
https://github.com/Warpnet/scantool.git
https://github.com/Gallopsled/pwntools.git
https://github.com/allfro/BurpKit.git
https://github.com/allfro/pymiproxy.git
https://github.com/darkoperator/dnsrecon.git
https://github.com/elceef/dnstwist.git
https://github.com/foxglovesec/Potato.git
https://github.com/packetfocus/Recon.git
https://github.com/iamchippa/dumpmon-scraper.git
https://github.com/Gradberry/Email-Permutator.git
https://github.com/aboul3la/Sublist3r.git
https://github.com/Kevin-Robertson/Tater
https://github.com/rsmudge/Malleable-C2-Profiles.git
https://github.com/leonteale/pentestpackage.git
https://github.com/JohnTroony/php-webshells.git
https://github.com/hardwaterhacker/URLCrazy.git
https://github.com/jaredhaight/PSAttack.git
https://github.com/mubix/post-exploitation.git
https://github.com/milo2012/pentest_scripts.git
https://github.com/sensepost/BiLE-suite.git
https://github.com/Raikia/SMBCrunch.git
https://github.com/Raikia/CredSwissArmy.git
https://github.com/ericevenchick/CANard.git
https://github.com/danielmiessler/ATM
https://github.com/linuz/Email-Verifier.git
https://github.com/khr0x40sh/MacroShop.git
https://github.com/thezawad/rev-door.git
https://github.com/Charliedean/psexecspray.git 
https://github.com/Hypsurus/weeman.git
https://github.com/eklitzke/c.sh.git
https://github.com/PowerShell/PowerShell.git
https://github.com/USArmyResearchLab/Dshell.git
https://github.com/znb/Scripts.git
EOF`
cd ../ 
for i in $a
do
git clone $i
done
